<x-filament-panels::page>
    <x-filament::section>
        <x-slot name="heading">Today's daily brief</x-slot>
        <x-slot name="description">
            Run the <code>editorial.daily_brief</code> agent to compose a markdown brief from the day's
            top stories, review it below, then send to {{ \App\Models\Subscription::active()->count() }} confirmed subscribers.
        </x-slot>

        @if (! empty($this->body))
            <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;padding:1.25rem 1.5rem;line-height:1.6;font-size:0.95rem;">
                {!! \Illuminate\Support\Str::markdown($this->body, [
                    'html_input' => 'strip',
                    'allow_unsafe_links' => false,
                ]) !!}
            </div>
            <p style="margin-top:0.75rem;color:#6b7280;font-size:0.8rem;">
                Generated by agent run #{{ $this->agentRunId ?? '—' }}.
                The "Open run record" action above shows the full transcript and tool calls.
            </p>
        @else
            <p style="color:#6b7280;">Click <strong>Generate brief</strong> above to compose today's edition.</p>
        @endif
    </x-filament::section>
</x-filament-panels::page>
