<?php

/**
 * CapstoneNMS — product-level configuration.
 *
 * The values in here describe the PRODUCT itself (its name, version,
 * homepage URL, license public key) and are NOT customer-editable.
 * Anything customer-editable lives in `getcong()` / Site Settings.
 *
 * Tier defaults define what each license tier permits. The actual
 * limits applied at runtime come from the license payload (so a
 * one-off enterprise deal can carry custom numbers without a code
 * change). These tier rows are the fallbacks the keygen CLI uses
 * when minting a license for a named tier and what the admin UI
 * shows when explaining what a tier includes.
 */

return [

    'product_name'    => 'CapstoneNMS',
    'product_url'     => 'https://capstonenms.com',
    'product_version' => '1.0.6-dev',

    /*
    |---------------------------------------------------------------
    | License public key
    |---------------------------------------------------------------
    | Ed25519 verification key (raw 32 bytes, base64-encoded).
    | The keygen CLI signs with the matching private key. The runtime
    | LicenseService verifies against this constant. Phase B will
    | populate this with a real key generated by `keygen/keygen
    | bootstrap`. Until then, the runtime treats every install as
    | unlicensed (see LicenseService::DEV_FALLBACK_TIER).
    */
    'license_public_key_b64' => env('CAPSTONE_LICENSE_PUBLIC_KEY', 'Z0nQaB0y4SdTN3ebPoEBGK65feVmD4KIq7c8JGFhfuA'),

    /*
    |---------------------------------------------------------------
    | Update manifest URL
    |---------------------------------------------------------------
    | Phase D: the admin "Updates" page hits this URL (signed JSON,
    | no auth) to discover available versions. Customers behind
    | air-gapped networks who can't reach this endpoint can still
    | download zip + signature manually and upload them through the
    | same admin UI.
    */
    'update_manifest_url' => env('CAPSTONE_UPDATE_MANIFEST_URL', 'https://update.capstonenms.com/manifest.json'),

    /*
    |---------------------------------------------------------------
    | Tier defaults
    |---------------------------------------------------------------
    | -1 means "unlimited". `feature_flags` describes which premium
    | features the tier unlocks. `force_powered_by_footer` makes the
    | "Powered by CapstoneNMS" footer mandatory; tiers with this
    | flag false let the customer hide it.
    */
    'tiers' => [
        'solo' => [
            'label'                    => 'Solo',
            'admins'                   => 1,
            'editors'                  => 0,
            'authors'                  => 0,
            'agents'                   => 1,
            'feature_flags'            => [],
            'force_powered_by_footer'  => true,
        ],
        'team' => [
            'label'                    => 'Team',
            'admins'                   => 2,
            'editors'                  => 3,
            'authors'                  => 10,
            'agents'                   => 3,
            'feature_flags'            => [],
            'force_powered_by_footer'  => false,
        ],
        'pro' => [
            'label'                    => 'Pro',
            'admins'                   => 5,
            'editors'                  => 10,
            'authors'                  => 25,
            'agents'                   => 10,
            'feature_flags'            => ['paywall'],
            'force_powered_by_footer'  => false,
        ],
        'enterprise' => [
            'label'                    => 'Enterprise',
            'admins'                   => -1,
            'editors'                  => -1,
            'authors'                  => -1,
            'agents'                   => -1,
            'feature_flags'            => ['paywall'],
            'force_powered_by_footer'  => false,
        ],
    ],

    /*
    |---------------------------------------------------------------
    | Domain matching
    |---------------------------------------------------------------
    | Hostnames in this list are always allowed regardless of the
    | license payload. They cover developer convenience without
    | letting a pirate run the product on `localhost` and proxy it
    | to the world (the LicenseService cross-checks APP_ENV and
    | refuses the localhost exemption when X-Forwarded-* headers
    | are present).
    */
    'always_allowed_hosts' => [
        'localhost',
        '127.0.0.1',
        '::1',
        '*.test',
        '*.local',
        '*.localhost',
    ],

    /*
    |---------------------------------------------------------------
    | License grace period
    |---------------------------------------------------------------
    | Days after a license expires during which the install keeps
    | working in read-only / no-update mode before a banner becomes
    | a hard lockout. Updates are gated immediately on expiry; the
    | rest of the product degrades gracefully through the grace
    | window so the customer has time to renew.
    */
    'expiry_grace_days' => 14,

];
